# Generated by Django 5.0.6 on 2024-07-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
