# Generated by Django 5.0.6 on 2024-07-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_wallet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram wallet'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter'),
        ),
    ]
