# Generated by Django 5.0.6 on 2024-08-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percent_for_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=30, verbose_name='percent')),
            ],
        ),
    ]
