# Generated by Django 5.0.6 on 2024-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_percent_for_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percent_for_content',
            name='percent',
            field=models.IntegerField(default=30, verbose_name='percent_for_content'),
        ),
    ]
