# Generated by Django 5.0.6 on 2024-08-14 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0020_remove_category_category_and_more'),
        ('posts', '0035_post_pit_main_page'),
        ('quests', '0014_remove_category_category_and_more'),
        ('surveys', '0016_remove_category_category_and_more'),
        ('users', '0011_alter_percent_for_content_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='quests_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quests.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='surveys_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='tests_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_tests.category'),
        ),
        migrations.CreateModel(
            name='Subcategory_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory_quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory_survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_tests.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
