# Generated by Django 5.0.6 on 2024-08-14 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_draftalbumphoto_draft_album'),
        ('users', '0012_user_posts_category_user_quests_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='albums_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.category'),
        ),
        migrations.CreateModel(
            name='Subcategory_album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
