# Generated by Django 5.0.6 on 2024-08-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_albums_category_subcategory_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory_album',
            old_name='subcategory_album',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory_post',
            old_name='subcategory_post',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory_quest',
            old_name='subcategory_quest',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory_survey',
            old_name='subcategory_survey',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory_test',
            old_name='subcategory_test',
            new_name='subcategory',
        ),
    ]
