# Generated by Django 5.0.6 on 2024-08-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_email'),
        ('users', '0014_rename_subcategory_album_subcategory_album_subcategory_and_more'),
    ]

    operations = [
    ]
