# Generated by Django 5.0.6 on 2024-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20240817_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Activity level'),
        ),
    ]
