# Generated by Django 5.0.6 on 2024-09-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20240819_2132'),
        ('users', '0016_user_activity_level'),
    ]

    operations = [
    ]
