# Generated by Django 5.0.6 on 2024-08-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_album_description_draftalbum_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
