# Generated by Django 5.0.6 on 2024-08-19 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_remove_album_likes_albumlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
