# Generated by Django 5.0.6 on 2024-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_draftalbumtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/albums/previews', verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='photo',
            field=models.ImageField(upload_to='uploads/albums/photos/', verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='draftalbum',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/albums/drafts/previews', verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='draftalbumphoto',
            name='photo',
            field=models.ImageField(upload_to='uploads/albums/drafts/photos/', verbose_name='Preview'),
        ),
    ]
