# Generated by Django 5.0.6 on 2024-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_album_size_albumphoto_size_draftalbum_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size preview (KB)'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size photo (KB)'),
        ),
        migrations.AlterField(
            model_name='draftalbum',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size preview (KB)'),
        ),
        migrations.AlterField(
            model_name='draftalbumphoto',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size photo (KB)'),
        ),
    ]
