# Generated by Django 5.0.6 on 2024-09-10 20:32

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_alter_album_size_alter_albumphoto_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.UploadToClass('uploads/albums/previews'), verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='photo',
            field=models.ImageField(upload_to=blog.utils.UploadToClass('uploads/albums/photos'), verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='draftalbum',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.UploadToClass('uploads/albums/drafts/previews'), verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='draftalbumphoto',
            name='photo',
            field=models.ImageField(upload_to=blog.utils.UploadToClass('uploads/albums/drafts/photos'), verbose_name='Preview'),
        ),
    ]
