# Generated by Django 5.0.6 on 2024-09-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0016_albumphoto_preview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftalbum',
            name='size',
        ),
        migrations.RemoveField(
            model_name='draftalbumphoto',
            name='size',
        ),
    ]
