# Generated by Django 5.0.6 on 2024-09-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0017_remove_draftalbum_size_remove_draftalbumphoto_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumphoto',
            old_name='preview_date',
            new_name='photo_date',
        ),
    ]
