# Generated by Django 5.0.6 on 2024-09-02 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Your follow expires in 3 days.', verbose_name='Text')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='expiring_follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.expiringfollow', verbose_name='Expiring follow'),
        ),
    ]
