# Generated by Django 5.0.6 on 2024-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_expiringfollow_notification_expiring_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='system_text',
            field=models.TextField(null=True, verbose_name='System text'),
        ),
    ]
