# Generated by Django 5.0.6 on 2024-09-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_system_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='system_text',
        ),
    ]
