# Generated by Django 5.0.6 on 2024-09-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_system_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='system_text',
            field=models.TextField(null=True, verbose_name='System text'),
        ),
    ]
