# Generated by Django 5.0.6 on 2024-07-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notificationpost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationsurvey',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='notificationsurvey',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationDonate',
        ),
        migrations.DeleteModel(
            name='NotificationPost',
        ),
        migrations.DeleteModel(
            name='NotificationSurvey',
        ),
    ]
