# Generated by Django 5.0.6 on 2024-09-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_notification_system_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='system_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.systemtext'),
        ),
    ]
