# Generated by Django 5.0.6 on 2024-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_systemtext_notification_system_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationblog',
            name='get_notifications_album',
            field=models.BooleanField(default=True, verbose_name='Get notifications for album'),
        ),
        migrations.AddField(
            model_name='notificationblog',
            name='get_notifications_post',
            field=models.BooleanField(default=True, verbose_name='Get notifications for post'),
        ),
        migrations.AddField(
            model_name='notificationblog',
            name='get_notifications_quest',
            field=models.BooleanField(default=True, verbose_name='Get notifications for quest'),
        ),
    ]
