# Generated by Django 5.0.6 on 2024-07-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notificationblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationblog',
            name='get_notifications_blog',
            field=models.BooleanField(default=True, verbose_name='Get notifications for blog'),
        ),
    ]
