# Generated by Django 5.0.6 on 2024-09-04 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_answer_album_comment_album'),
        ('notifications', '0008_notificationblog_get_notifications_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.answer', verbose_name='Answer'),
        ),
    ]
