# Generated by Django 5.0.6 on 2024-07-09 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notificationblog_get_notifications_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationblog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_blog', to=settings.AUTH_USER_MODEL, verbose_name='User of blog'),
            preserve_default=False,
        ),
    ]
