# Generated by Django 5.0.6 on 2024-07-09 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notificationblog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 9, 18, 36, 46, 773310, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
