# Generated by Django 5.0.6 on 2024-09-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='answer',
        ),
    ]
