# Generated by Django 5.0.6 on 2024-07-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0014_alter_test_hide_to_user'),
        ('notifications', '0010_notification_date'),
        ('quests', '0010_quest_blog_quest_level_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quests.quest', verbose_name='Quest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_tests.test', verbose_name='Test'),
        ),
    ]
