# Generated by Django 5.0.6 on 2024-09-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_answer_album_comment_album'),
        ('notifications', '0010_remove_notification_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(verbose_name='Url')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.answer', verbose_name='Answer')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='answer_notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.answernotification', verbose_name='Answer notification'),
        ),
    ]
