# Generated by Django 5.0.6 on 2024-09-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_answernotification_notification_answer_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answernotification',
            name='url',
        ),
    ]
