# Generated by Django 5.0.6 on 2024-08-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_albumphoto'),
        ('notifications', '0011_notification_quest_notification_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Album'),
        ),
    ]
