# Generated by Django 5.0.6 on 2024-08-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_contest_is_end'),
        ('notifications', '0012_notification_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.contest', verbose_name='Contest'),
        ),
    ]
