# Generated by Django 5.0.6 on 2024-09-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_remove_answernotification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='answernotification',
            name='namespace',
            field=models.CharField(default=1, verbose_name='Namespace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answernotification',
            name='slug',
            field=models.CharField(default=1, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
