# Generated by Django 5.0.6 on 2024-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_answernotification_namespace_answernotification_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationblog',
            name='get_notifications_answer',
            field=models.BooleanField(default=True, verbose_name='Get notifications for answer'),
        ),
    ]
