# Generated by Django 5.0.6 on 2024-09-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_notificationblog_get_notifications_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemtext',
            name='text',
        ),
        migrations.AddField(
            model_name='systemtext',
            name='text_eng',
            field=models.TextField(default=1, verbose_name='Text eng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemtext',
            name='text_rus',
            field=models.TextField(default=1, verbose_name='Text rus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemtext',
            name='title_eng',
            field=models.CharField(default=1, verbose_name='Title eng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemtext',
            name='title_rus',
            field=models.CharField(default=1, verbose_name='Title rus'),
            preserve_default=False,
        ),
    ]
