# Generated by Django 5.0.6 on 2024-09-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_remove_systemtext_text_systemtext_text_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemtext',
            name='english',
            field=models.BooleanField(default=True, verbose_name='English'),
        ),
        migrations.AddField(
            model_name='systemtext',
            name='russian',
            field=models.BooleanField(default=True, verbose_name='Russian'),
        ),
    ]
