# Generated by Django 5.0.6 on 2024-08-26 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_draftalbumtag'),
        ('contests', '0011_contest_is_end'),
        ('notifications', '0016_remove_notification_contest_alter_notification_user_and_more'),
        ('posts', '0042_remove_post_likes_postlike'),
        ('quests', '0017_questtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotifiticationContest',
            new_name='NotificationContest',
        ),
    ]
