# Generated by Django 5.0.6 on 2024-09-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_alter_systemtext_text_eng_alter_systemtext_text_rus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtext',
            name='text_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Text eng'),
        ),
        migrations.AlterField(
            model_name='systemtext',
            name='text_rus',
            field=models.TextField(blank=True, null=True, verbose_name='Text rus'),
        ),
        migrations.AlterField(
            model_name='systemtext',
            name='title_eng',
            field=models.CharField(blank=True, null=True, verbose_name='Title eng'),
        ),
        migrations.AlterField(
            model_name='systemtext',
            name='title_rus',
            field=models.CharField(blank=True, null=True, verbose_name='Title rus'),
        ),
    ]
