# Generated by Django 5.0.6 on 2024-08-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_draftalbumtag'),
        ('notifications', '0017_rename_notifiticationcontest_notificationcontest'),
        ('posts', '0042_remove_post_likes_postlike'),
        ('quests', '0017_questtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationcontest',
            name='album',
        ),
        migrations.RemoveField(
            model_name='notificationcontest',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notificationcontest',
            name='quest',
        ),
        migrations.AddField(
            model_name='notificationcontest',
            name='contest_album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Contest album'),
        ),
        migrations.AddField(
            model_name='notificationcontest',
            name='contest_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Contest post'),
        ),
        migrations.AddField(
            model_name='notificationcontest',
            name='contest_quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quests.quest', verbose_name='Contest uest'),
        ),
    ]
