# Generated by Django 5.0.6 on 2024-08-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_remove_notificationcontest_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcontest',
            name='text',
            field=models.CharField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
