# Generated by Django 5.0.6 on 2024-09-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_systemtext_text_eng_alter_systemtext_text_rus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='system_text',
        ),
    ]
