# Generated by Django 5.0.6 on 2024-08-26 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_draftalbumtag'),
        ('contests', '0011_contest_is_end'),
        ('notifications', '0019_notificationcontest_text'),
        ('posts', '0042_remove_post_likes_postlike'),
        ('quests', '0017_questtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='contest_album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_album', to='albums.album', verbose_name='Contest album'),
        ),
        migrations.AddField(
            model_name='notification',
            name='contest_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_post', to='posts.post', verbose_name='Contest post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='contest_quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_quest', to='quests.quest', verbose_name='Contest uest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(null=True, verbose_name='Text'),
        ),
        migrations.DeleteModel(
            name='NotificationContest',
        ),
    ]
