# Generated by Django 5.0.6 on 2024-09-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_remove_notification_ban_notification_system_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.ban', verbose_name='Ban'),
        ),
    ]
