# Generated by Django 5.0.6 on 2024-08-06 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('scores', models.IntegerField(default=100, verbose_name='Scores')),
                ('interval', models.PositiveIntegerField(help_text='Interval in hours', verbose_name='Interval')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Periodic bonus',
                'verbose_name_plural': 'Periodic bonuses',
            },
        ),
        migrations.CreateModel(
            name='ReceivingPeriodicPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='received date')),
                ('is_received', models.BooleanField(default=False, verbose_name='is received')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('periodic_bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_periodic_points', to='periodic_bonuses.periodicbonuses', verbose_name='Periodic bonus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_periodic_points', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Receiving periodic points',
                'verbose_name_plural': 'Receiving periodic points',
            },
        ),
    ]
