# Generated by Django 5.0.6 on 2024-08-12 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_albumphoto'),
        ('comments', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Album'),
        ),
        migrations.AddField(
            model_name='comment',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Album'),
        ),
    ]
