# Generated by Django 5.0.6 on 2024-07-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_survey_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsurvey',
            name='language',
            field=models.CharField(blank=True, null=True, verbose_name='Language'),
        ),
    ]
