# Generated by Django 5.0.6 on 2024-07-10 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_remove_paidfollow_count_mouths_and_more'),
        ('surveys', '0006_draftsurvey_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftsurvey',
            name='level_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.levelaccess', verbose_name='Level access'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='level_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.levelaccess', verbose_name='Level access'),
        ),
    ]
