# Generated by Django 5.0.6 on 2024-07-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_category_survey_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsurvey',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='draftsurvey',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.subcategory', verbose_name='Subcategory'),
        ),
    ]
