# Generated by Django 5.0.6 on 2024-08-05 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_remove_surveyview_day_remove_surveyview_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydayview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_survey_day', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveyweekview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_survey_week', to=settings.AUTH_USER_MODEL),
        ),
    ]
