# Generated by Django 5.0.6 on 2024-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_alter_surveydayview_user_alter_surveyweekview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='namespace',
            field=models.CharField(default='surveys', verbose_name='Namespace'),
        ),
    ]
