# Generated by Django 5.0.6 on 2024-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_remove_survey_likes_surveylike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftsurvey',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/surveys/drafts/previews', verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/surveys/previews', verbose_name='Preview'),
        ),
    ]
