# Generated by Django 5.0.6 on 2024-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_draftsurvey_preview_alter_survey_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsurvey',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size preview (KB)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size preview (KB)'),
        ),
    ]
