# Generated by Django 5.0.6 on 2024-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_draftsurvey_size_survey_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftsurvey',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size preview (KB)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size preview (KB)'),
        ),
    ]
