# Generated by Django 5.0.6 on 2024-09-10 20:32

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_alter_draftsurvey_size_alter_survey_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftsurvey',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.UploadToClass('uploads/surveys/drafts/previews'), verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.UploadToClass('uploads/surveys/previews'), verbose_name='Preview'),
        ),
    ]
