# Generated by Django 5.0.6 on 2024-09-11 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_alter_draftsurvey_preview_alter_survey_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='preview_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
