# Generated by Django 5.0.6 on 2024-08-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_campaign', models.PositiveIntegerField(default=10, verbose_name='Лимит компаний для одного пользователя')),
                ('periodic_scores', models.PositiveIntegerField(default=100, verbose_name='Количество баллов периодического бонуса')),
                ('twitter_connect_scores', models.PositiveIntegerField(default=150, verbose_name='Баллы за подключения Twitter аккаунта')),
                ('telegram_wallet_connect_scores', models.PositiveIntegerField(default=200, verbose_name='Баллы за подключение кошелька Telegram')),
                ('point_invitation_by_referral_link', models.PositiveIntegerField(default=500, verbose_name='Награда (в баллах) за каждого приглашенного пользователя по реферальной ссылке')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
    ]
