# Generated by Django 5.0.6 on 2024-08-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCoefficients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_num', models.PositiveIntegerField(verbose_name='From')),
                ('to_num', models.PositiveIntegerField(verbose_name='To')),
                ('coefficient', models.FloatField(verbose_name='Coefficient')),
            ],
            options={
                'verbose_name': 'Bonus coefficient',
                'verbose_name_plural': 'Bonus coefficients',
            },
        ),
    ]
