# Generated by Django 5.0.6 on 2024-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField()),
                ('prize_fund', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='campaign_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('telegram_subscription', 'Telegram Subscription'), ('twitter_subscription', 'Twitter Subscription'), ('website_visit', 'Website Visit'), ('content_creation', 'Content Creation'), ('content_usage', 'Content Usage'), ('comment', 'Comment'), ('wallet_connect', 'Wallet Connect'), ('twitter_connect', 'Twitter Connect'), ('periodic_bonus', 'Periodic Bonus'), ('referral_registration', 'Referral Registration')], max_length=50)),
                ('content_usage_type', models.CharField(blank=True, choices=[('test', 'Test'), ('quest', 'Quest'), ('post', 'Post'), ('survey', 'Survey'), ('comment', 'Comment')], max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points_reward', models.IntegerField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('total_pool_points', models.IntegerField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTaskChecking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is completed')),
                ('points_awarded', models.IntegerField(default=0, verbose_name='Points')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
            ],
        ),
    ]
