# Generated by Django 5.0.6 on 2024-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField()),
                ('prize_fund', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='campaign_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('telegram_subscription', 'Telegram Subscription'), ('twitter_subscription', 'Twitter Subscription'), ('website_visit', 'Website Visit'), ('content_creation', 'Content Creation'), ('content_usage', 'Content Usage'), ('comment', 'Comment'), ('wallet_connect', 'Wallet Connect'), ('twitter_connect', 'Twitter Connect'), ('periodic_bonus', 'Periodic Bonus'), ('referral_registration', 'Referral Registration')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('points_reward', models.IntegerField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('total_pool_points', models.IntegerField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True)),
            ],
        ),
    ]
