# Generated by Django 5.0.6 on 2024-07-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
