# Generated by Django 5.0.6 on 2024-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='reward_source',
            field=models.CharField(choices=[('owner', 'Владелец компании'), ('endless', 'Бесконечный')], default='owner', max_length=50, verbose_name='Источник награды кампании'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='usertaskchecking',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='Is received'),
        ),
        migrations.AddField(
            model_name='usertaskchecking',
            name='received_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Received data'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='prize_fund',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
