# Generated by Django 5.0.6 on 2024-07-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_task_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
