# Generated by Django 5.0.6 on 2024-08-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaign_reward_source_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('telegram_subscription', 'Telegram Subscription'), ('twitter_subscription', 'Twitter Subscription'), ('website_visit', 'Website Visit'), ('content_creation', 'Content Creation'), ('content_usage', 'Content Usage'), ('comment', 'Comment'), ('wallet_connect', 'Wallet Connect'), ('twitter_connect', 'Twitter Connect'), ('periodic_bonus', 'Periodic Bonus')], max_length=50),
        ),
    ]
