# Generated by Django 5.0.6 on 2024-07-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
