# Generated by Django 5.0.6 on 2024-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_subscriptionscampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionscampaign',
            name='campaigns',
            field=models.ManyToManyField(null=True, to='campaign.campaign', verbose_name='Campaign'),
        ),
    ]
