# Generated by Django 5.0.6 on 2024-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_remove_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content_usage_type',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('quest', 'Quest'), ('post', 'Post'), ('survey', 'Survey'), ('comment', 'Comment')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
