# Generated by Django 5.0.6 on 2024-09-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_alter_subscriptionscampaign_campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionscampaign',
            name='campaigns',
            field=models.ManyToManyField(to='campaign.campaign', verbose_name='Campaign'),
        ),
    ]
