# Generated by Django 5.0.6 on 2024-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_alter_subscriptionscampaign_campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/campaigns/previews'),
        ),
    ]
