# Generated by Django 5.0.6 on 2024-09-11 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_alter_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
