# Generated by Django 5.0.6 on 2024-08-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('awaiting receipt confirmation', 'Awaiting receipt confirmation'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=255, verbose_name='Status'),
        ),
    ]
