# Generated by Django 5.0.6 on 2024-08-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='language',
            field=models.CharField(default=1, max_length=255, verbose_name='Language'),
            preserve_default=False,
        ),
    ]
