# Generated by Django 5.0.6 on 2024-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='album',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='post',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='quest',
        ),
        migrations.AddField(
            model_name='contest',
            name='item_type',
            field=models.CharField(default=1, verbose_name='Item type (post, quest, album)'),
            preserve_default=False,
        ),
    ]
