# Generated by Django 5.0.6 on 2024-08-21 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_alter_contest_options_contest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 16, 53, 59, 759179, tzinfo=datetime.timezone.utc), verbose_name='Start date'),
        ),
    ]
