# Generated by Django 5.0.6 on 2024-08-21 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_contest_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
    ]
