# Generated by Django 5.0.6 on 2024-08-23 17:02

import blog.validators
import contests.api.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_draftalbumtag'),
        ('contests', '0006_alter_contest_start_date'),
        ('posts', '0042_remove_post_likes_postlike'),
        ('quests', '0017_questtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='criteries',
            field=models.CharField(choices=[('likes', 'Likes'), ('views', 'Views'), ('assessment', 'Assessment')], validators=[contests.api.validators.check_criteries], verbose_name='Criteries'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='item_type',
            field=models.CharField(choices=[('post', 'Post'), ('album', 'Album'), ('quest', 'Quest')], validators=[contests.api.validators.check_item_type], verbose_name='Item type'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('russian', 'Russian')], max_length=255, validators=[blog.validators.check_language], verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='AlbumElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
            ],
        ),
        migrations.CreateModel(
            name='PostElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='QuestElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.quest')),
            ],
        ),
    ]
