# Generated by Django 5.0.6 on 2024-08-25 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_albumelement_user_postelement_user_questelement_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeAlbumElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_album_place', to='contests.contest')),
                ('eight_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight_album_place', to='contests.albumelement')),
                ('five_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five_album_place', to='contests.albumelement')),
                ('four_lace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four_album_place', to='contests.albumelement')),
                ('nine_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nine_album_place', to='contests.albumelement')),
                ('one_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_album_place', to='contests.albumelement')),
                ('seven_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven_album_place', to='contests.albumelement')),
                ('six_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six_album_place', to='contests.albumelement')),
                ('ten_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ten_album_place', to='contests.albumelement')),
                ('three_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_album_place', to='contests.albumelement')),
                ('two_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_album_place', to='contests.albumelement')),
            ],
        ),
        migrations.CreateModel(
            name='PrizePostElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_post_place', to='contests.contest')),
                ('eight_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight_post_place', to='contests.postelement')),
                ('five_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five_post_place', to='contests.postelement')),
                ('four_lace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four_post_place', to='contests.postelement')),
                ('nine_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nine_post_place', to='contests.postelement')),
                ('one_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_post_place', to='contests.postelement')),
                ('seven_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven_post_place', to='contests.postelement')),
                ('six_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six_post_place', to='contests.postelement')),
                ('ten_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ten_post_place', to='contests.postelement')),
                ('three_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_post_place', to='contests.postelement')),
                ('two_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_post_place', to='contests.postelement')),
            ],
        ),
        migrations.CreateModel(
            name='PrizeQuestElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_quest_place', to='contests.contest')),
                ('eight_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight_quest_place', to='contests.questelement')),
                ('five_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five_quest_place', to='contests.questelement')),
                ('four_lace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four_quest_place', to='contests.questelement')),
                ('nine_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nine_quest_place', to='contests.questelement')),
                ('one_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_quest_place', to='contests.questelement')),
                ('seven_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven_quest_place', to='contests.questelement')),
                ('six_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six_quest_place', to='contests.questelement')),
                ('ten_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ten_quest_place', to='contests.questelement')),
                ('three_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_quest_place', to='contests.questelement')),
                ('two_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_quest_place', to='contests.questelement')),
            ],
        ),
    ]
