# Generated by Django 5.0.6 on 2024-08-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_draftalbumtag'),
        ('contests', '0009_prizealbumelement_prizepostelement_prizequestelement'),
        ('posts', '0042_remove_post_likes_postlike'),
        ('quests', '0017_questtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizealbumelement',
            name='eight_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight_album_place', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='prizealbumelement',
            name='five_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five_album_place', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='prizealbumelement',
            name='four_lace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four_album_place', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='prizealbumelement',
            name='nine_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nine_album_place', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='prizealbumelement',
            name='one_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_album_place', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='prizealbumelement',
            name='seven_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven_album_place', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='prizealbumelement',
            name='six_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six_album_place', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='prizealbumelement',
            name='ten_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ten_album_place', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='prizealbumelement',
            name='three_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_album_place', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='prizealbumelement',
            name='two_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_album_place', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='prizepostelement',
            name='eight_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight_post_place', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='prizepostelement',
            name='five_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five_post_place', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='prizepostelement',
            name='four_lace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four_post_place', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='prizepostelement',
            name='nine_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nine_post_place', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='prizepostelement',
            name='one_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_post_place', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='prizepostelement',
            name='seven_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven_post_place', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='prizepostelement',
            name='six_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six_post_place', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='prizepostelement',
            name='ten_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ten_post_place', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='prizepostelement',
            name='three_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_post_place', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='prizepostelement',
            name='two_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_post_place', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='prizequestelement',
            name='eight_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight_quest_place', to='quests.quest'),
        ),
        migrations.AlterField(
            model_name='prizequestelement',
            name='five_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five_quest_place', to='quests.quest'),
        ),
        migrations.AlterField(
            model_name='prizequestelement',
            name='four_lace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four_quest_place', to='quests.quest'),
        ),
        migrations.AlterField(
            model_name='prizequestelement',
            name='nine_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nine_quest_place', to='quests.quest'),
        ),
        migrations.AlterField(
            model_name='prizequestelement',
            name='one_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_quest_place', to='quests.quest'),
        ),
        migrations.AlterField(
            model_name='prizequestelement',
            name='seven_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven_quest_place', to='quests.quest'),
        ),
        migrations.AlterField(
            model_name='prizequestelement',
            name='six_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six_quest_place', to='quests.quest'),
        ),
        migrations.AlterField(
            model_name='prizequestelement',
            name='ten_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ten_quest_place', to='quests.quest'),
        ),
        migrations.AlterField(
            model_name='prizequestelement',
            name='three_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_quest_place', to='quests.quest'),
        ),
        migrations.AlterField(
            model_name='prizequestelement',
            name='two_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_quest_place', to='quests.quest'),
        ),
    ]
