# Generated by Django 5.0.6 on 2024-08-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_alter_prizealbumelement_eight_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='Is end'),
        ),
    ]
