# Generated by Django 5.0.6 on 2024-09-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_contest_is_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prizealbumelement',
            options={'verbose_name': 'Album prize', 'verbose_name_plural': 'Album prizes'},
        ),
        migrations.AlterModelOptions(
            name='prizepostelement',
            options={'verbose_name': 'Post prize', 'verbose_name_plural': 'Post prizes'},
        ),
        migrations.AlterModelOptions(
            name='prizequestelement',
            options={'verbose_name': 'Quest prize', 'verbose_name_plural': 'Quest prizes'},
        ),
    ]
