# Generated by Django 5.0.6 on 2024-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_alter_prizealbumelement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/contests/previews', verbose_name='Preview'),
        ),
    ]
