# Generated by Django 5.0.6 on 2024-09-10 20:32

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_alter_contest_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.UploadToClass('uploads/contests/previews'), verbose_name='Preview'),
        ),
    ]
