# Generated by Django 5.0.6 on 2024-09-11 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_alter_contest_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='preview_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
