# Generated by Django 5.0.6 on 2024-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('preview', models.ImageField(upload_to='upload_blogs/', verbose_name='Preview')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is private')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='LevelAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Level access')),
                ('scores', models.IntegerField(default=0, verbose_name='Scores')),
            ],
        ),
        migrations.CreateModel(
            name='PaidFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Expiration date')),
                ('count_mouths', models.IntegerField(default=1, verbose_name='Count mouths')),
            ],
        ),
    ]
