# Generated by Django 5.0.6 on 2024-07-04 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=datetime.datetime(2024, 7, 4, 12, 7, 43, 910343, tzinfo=datetime.timezone.utc), verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(default='test', max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
