# Generated by Django 5.0.6 on 2024-07-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blog_slug_blog_description_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
