# Generated by Django 5.0.6 on 2024-07-04 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='URL'),
        ),
    ]
