# Generated by Django 5.0.6 on 2024-07-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
            preserve_default=False,
        ),
    ]
