# Generated by Django 5.0.6 on 2024-07-05 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_donate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 7, 5, 11, 26, 16, 114133, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
