# Generated by Django 5.0.6 on 2024-07-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_donate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
