# Generated by Django 5.0.6 on 2024-07-10 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_donate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelaccess',
            name='level',
        ),
        migrations.AddField(
            model_name='levelaccess',
            name='description',
            field=models.TextField(default=datetime.datetime(2024, 7, 10, 14, 6, 3, 845028, tzinfo=datetime.timezone.utc), verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='levelaccess',
            name='preview',
            field=models.ImageField(default=datetime.datetime(2024, 7, 10, 14, 6, 10, 531772, tzinfo=datetime.timezone.utc), upload_to='upload_follows/', verbose_name='Preview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='levelaccess',
            name='title',
            field=models.CharField(default='dasas', unique=True, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
