# Generated by Django 5.0.6 on 2024-07-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_remove_levelaccess_level_levelaccess_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelaccess',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level access'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='levelaccess',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='upload_follows/', verbose_name='Preview'),
        ),
    ]
