# Generated by Django 5.0.6 on 2024-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_levelaccess_level_alter_levelaccess_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelaccess',
            name='preview',
            field=models.ImageField(default=1, upload_to='upload_follows/', verbose_name='Preview'),
            preserve_default=False,
        ),
    ]
