# Generated by Django 5.0.6 on 2024-07-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_alter_levelaccess_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidfollow',
            name='count_mouths',
        ),
        migrations.AddField(
            model_name='paidfollow',
            name='count_months',
            field=models.IntegerField(default=1, verbose_name='Count months'),
        ),
    ]
