# Generated by Django 5.0.6 on 2024-07-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_blogfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelaccess',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title'),
        ),
    ]
