# Generated by Django 5.0.6 on 2024-07-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_alter_levelaccess_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(verbose_name='Category')),
                ('subcategory', models.CharField(blank=True, null=True, verbose_name='Subcategory')),
            ],
        ),
    ]
