# Generated by Django 5.0.6 on 2024-07-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_remove_category_subcategory_subcategory'),
        ('posts', '0028_category_alter_post_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
