# Generated by Django 5.0.6 on 2024-08-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
