# Generated by Django 5.0.6 on 2024-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(upload_to='uploads/blogs/previews', verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='levelaccess',
            name='preview',
            field=models.ImageField(upload_to='uploads/blogs/follows', verbose_name='Preview'),
        ),
    ]
