# Generated by Django 5.0.6 on 2024-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_alter_blog_preview_alter_levelaccess_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size preview (KB)'),
        ),
    ]
