# Generated by Django 5.0.6 on 2024-09-10 20:32

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_alter_blog_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(upload_to=blog.utils.UploadToClass('uploads/blogs/follows'), verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='levelaccess',
            name='preview',
            field=models.ImageField(upload_to=blog.utils.UploadToClass('uploads/blogs/follows'), verbose_name='Preview'),
        ),
    ]
