# Generated by Django 5.0.6 on 2024-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='quests/', verbose_name='Preview'),
        ),
    ]
