# Generated by Django 5.0.6 on 2024-07-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_alter_quest_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
