# Generated by Django 5.0.6 on 2024-07-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_alter_quest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='language',
            field=models.CharField(verbose_name='Language'),
        ),
    ]
