# Generated by Django 5.0.6 on 2024-07-20 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_alter_quest_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
