# Generated by Django 5.0.6 on 2024-07-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_quest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='namespace',
            field=models.CharField(default='quests', verbose_name='Namespace'),
        ),
    ]
