# Generated by Django 5.0.6 on 2024-07-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_quest_namespace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='date',
        ),
        migrations.AlterField(
            model_name='quest',
            name='language',
            field=models.CharField(max_length=255, verbose_name='Language'),
        ),
    ]
