# Generated by Django 5.0.6 on 2024-07-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0010_quest_blog_quest_level_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quests.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(verbose_name='Subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.category', verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='subcategory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quests.subcategory', verbose_name='Subcategory'),
            preserve_default=False,
        ),
    ]
