# Generated by Django 5.0.6 on 2024-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0011_category_quest_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questview',
            name='day',
            field=models.IntegerField(default=0, verbose_name='Day view'),
        ),
        migrations.AddField(
            model_name='questview',
            name='week',
            field=models.IntegerField(default=0, verbose_name='Week view'),
        ),
    ]
