# Generated by Django 5.0.6 on 2024-08-05 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0012_questview_day_questview_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questview',
            name='day',
        ),
        migrations.RemoveField(
            model_name='questview',
            name='week',
        ),
        migrations.CreateModel(
            name='QuestDayView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_day', to='quests.quest', verbose_name='Quest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quest_day', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestWeekView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_week', to='quests.quest', verbose_name='Quest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quest_week', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
