# Generated by Django 5.0.6 on 2024-08-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0014_remove_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
