# Generated by Django 5.0.6 on 2024-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0017_questtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/quests/previews', verbose_name='Preview'),
        ),
    ]
