# Generated by Django 5.0.6 on 2024-09-11 20:49

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0020_alter_quest_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.UploadToClass('uploads/quests/previews'), verbose_name='Preview'),
        ),
    ]
