# Generated by Django 5.0.6 on 2024-09-11 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0021_alter_quest_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='preview_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
