# Generated by Django 5.0.6 on 2024-07-13 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('preview', models.ImageField(upload_to='uploads/', verbose_name='Preview')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('language', models.CharField(choices=[('1', 'English'), ('2', 'Russian')], max_length=255, verbose_name='Language')),
                ('scores', models.IntegerField(default=0, verbose_name='scores')),
                ('hide_to_moderator', models.BooleanField(default=False, verbose_name='Hide to moderator')),
                ('hide_to_user', models.BooleanField(default=True, verbose_name='Hide to user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timer', models.IntegerField(blank=True, help_text='Example: 10 (minute) or leave blank', null=True, verbose_name='Timer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=250, verbose_name='Question answer')),
                ('is_true', models.BooleanField(default=False, verbose_name='True Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='custom_tests.question', verbose_name='Question')),
            ],
        ),
    ]
