# Generated by Django 5.0.6 on 2024-07-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0004_alter_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='language',
            field=models.CharField(verbose_name='Language'),
        ),
    ]
