# Generated by Django 5.0.6 on 2024-07-20 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0005_alter_test_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 20, 11, 58, 29, 832245, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
