# Generated by Django 5.0.6 on 2024-07-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0007_test_namespace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date',
        ),
        migrations.AlterField(
            model_name='test',
            name='language',
            field=models.CharField(max_length=255, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='test',
            name='namespace',
            field=models.CharField(default='posts', verbose_name='Namespace'),
        ),
    ]
