# Generated by Django 5.0.6 on 2024-07-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0008_remove_test_date_alter_test_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden for post'),
        ),
    ]
