# Generated by Django 5.0.6 on 2024-07-27 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0010_alter_test_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='test',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
