# Generated by Django 5.0.6 on 2024-07-27 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_alter_levelaccess_title'),
        ('custom_tests', '0012_testview'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='level_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.levelaccess', verbose_name='Level access'),
        ),
    ]
