# Generated by Django 5.0.6 on 2024-07-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0013_test_blog_test_level_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='hide_to_user',
            field=models.BooleanField(default=False, verbose_name='Hide to user'),
        ),
    ]
