# Generated by Django 5.0.6 on 2024-07-29 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0014_alter_test_hide_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_tests.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(verbose_name='Subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_tests.category', verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_tests.subcategory', verbose_name='Subcategory'),
        ),
    ]
