# Generated by Django 5.0.6 on 2024-07-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0015_category_test_category_subcategory_test_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_tests.subcategory', verbose_name='Subcategory'),
        ),
    ]
