# Generated by Django 5.0.6 on 2024-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0018_remove_testview_day_remove_testview_week_testdayview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='namespace',
            field=models.CharField(default='tests', verbose_name='Namespace'),
        ),
    ]
