# Generated by Django 5.0.6 on 2024-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0022_remove_test_likes_testlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tests/previews', verbose_name='Preview'),
        ),
    ]
