# Generated by Django 5.0.6 on 2024-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0023_alter_test_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size preview (KB)'),
        ),
    ]
