# Generated by Django 5.0.6 on 2024-09-10 20:32

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0025_alter_test_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.UploadToClass('uploads/tests/previews'), verbose_name='Preview'),
        ),
    ]
