# Generated by Django 5.0.6 on 2024-09-11 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0026_alter_test_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='preview_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
