# Generated by Django 5.0.6 on 2024-07-19 13:16

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField(verbose_name='scores')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='uploads_drafts/', verbose_name='Preview')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('language', models.CharField(blank=True, max_length=255, null=True, verbose_name='Language')),
                ('add_survey', models.BooleanField(default=False, verbose_name='Add survey')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Draft',
                'verbose_name_plural': 'Drafts',
            },
        ),
        migrations.CreateModel(
            name='DraftPostRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Radio',
                'verbose_name_plural': 'Radios',
            },
        ),
        migrations.CreateModel(
            name='DraftPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Preview')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('language', models.CharField(max_length=255, verbose_name='Language')),
                ('scores', models.IntegerField(default=0, verbose_name='scores')),
                ('mouth_scores', models.IntegerField(default=0, verbose_name='Mouth scores')),
                ('hide_to_user', models.BooleanField(default=False, verbose_name='Hide to user')),
                ('hide_to_moderator', models.BooleanField(default=False, verbose_name='Hide to moderator')),
                ('add_survey', models.BooleanField(default=False, verbose_name='Add survey')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
            managers=[
                ('level_access_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField(default=0, verbose_name='scores')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Radio',
                'verbose_name_plural': 'Radios',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'View',
                'verbose_name_plural': 'Views',
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=250, verbose_name='Question answer')),
                ('is_true', models.BooleanField(default=False, verbose_name='True Answer')),
            ],
        ),
    ]
