# Generated by Django 5.0.6 on 2024-07-13 11:29

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('preview', models.ImageField(upload_to='uploads/', verbose_name='Preview')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('language', models.CharField(choices=[('1', 'English'), ('2', 'Russian')], max_length=255, verbose_name='Language')),
                ('scores', models.IntegerField(default=0, verbose_name='scores')),
                ('mouth_scores', models.IntegerField(default=0, verbose_name='Mouth scores')),
                ('hide_to_user', models.BooleanField(default=False, verbose_name='Hide to user')),
                ('hide_to_moderator', models.BooleanField(default=False, verbose_name='Hide to moderator')),
                ('level_access', models.IntegerField(default=0, verbose_name='Level access')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
            managers=[
                ('level_access_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'View',
                'verbose_name_plural': 'Views',
            },
        ),
        migrations.CreateModel(
            name='DraftPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='uploads_drafts/', verbose_name='Preview')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('level_access', models.IntegerField(default=0, verbose_name='Level access')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
            ],
            options={
                'verbose_name': 'Draft',
                'verbose_name_plural': 'Drafts',
            },
        ),
    ]
