# Generated by Django 5.0.6 on 2024-07-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid'),
        ),
    ]
