# Generated by Django 5.0.6 on 2024-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_buypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='buypost',
            name='scores',
            field=models.IntegerField(default=0, verbose_name='scores'),
            preserve_default=False,
        ),
    ]
