# Generated by Django 5.0.6 on 2024-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_buypost_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Preview'),
        ),
    ]
