# Generated by Django 5.0.6 on 2024-07-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
