# Generated by Django 5.0.6 on 2024-07-06 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postradio_postvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPostRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('draft_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.draftpost', verbose_name='Draft post')),
            ],
            options={
                'verbose_name': 'Radio',
                'verbose_name_plural': 'Radios',
            },
        ),
    ]
