# Generated by Django 5.0.6 on 2024-07-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_add_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='posts.post', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=250, verbose_name='Question answer')),
                ('is_true', models.BooleanField(default=False, verbose_name='True Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='posts.question', verbose_name='Question')),
            ],
        ),
    ]
