# Generated by Django 5.0.6 on 2024-07-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_question_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpost',
            name='add_survey',
            field=models.BooleanField(default=False, verbose_name='Add survey'),
        ),
    ]
