# Generated by Django 5.0.6 on 2024-07-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpost',
            name='language',
            field=models.CharField(blank=True, null=True, verbose_name='Language'),
        ),
    ]
