# Generated by Django 5.0.6 on 2024-07-10 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_alter_levelaccess_preview'),
        ('posts', '0016_draftpost_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='level_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.levelaccess', verbose_name='Level access'),
        ),
    ]
