# Generated by Django 5.0.6 on 2024-07-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_draftpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='namespace',
            field=models.CharField(default='posts', verbose_name='Namespace'),
        ),
    ]
