# Generated by Django 5.0.6 on 2024-07-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_draftpost_language_alter_post_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
