# Generated by Django 5.0.6 on 2024-07-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0010_alter_test_managers'),
        ('posts', '0022_remove_questionanswer_question_delete_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_tests.test', verbose_name='Test'),
        ),
    ]
