# Generated by Django 5.0.6 on 2024-07-26 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tests', '0010_alter_test_managers'),
        ('posts', '0023_post_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_tests.test', verbose_name='Test'),
        ),
    ]
