# Generated by Django 5.0.6 on 2024-07-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_post_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpost',
            name='test',
            field=models.BooleanField(default=False, verbose_name='Test'),
        ),
    ]
