# Generated by Django 5.0.6 on 2024-07-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_draftpost_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftpost',
            old_name='test',
            new_name='is_create_test',
        ),
    ]
