# Generated by Django 5.0.6 on 2024-07-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_remove_category_subcategory_subcategory'),
        ('posts', '0026_rename_test_draftpost_is_create_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.subcategory', verbose_name='Subcategory'),
        ),
    ]
