# Generated by Django 5.0.6 on 2024-07-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_draftpost_category_draftpost_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpost',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.subcategory', verbose_name='Subcategory'),
            preserve_default=False,
        ),
    ]
