# Generated by Django 5.0.6 on 2024-07-29 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_alter_draftpost_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='draftpost',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.subcategory', verbose_name='Subcategory'),
        ),
    ]
