# Generated by Django 5.0.6 on 2024-08-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_remove_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pit_main_page',
            field=models.CharField(blank=True, null=True, verbose_name='Pin it to the main page'),
        ),
    ]
