# Generated by Django 5.0.6 on 2024-08-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_post_pit_main_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pit_main_page',
        ),
    ]
