# Generated by Django 5.0.6 on 2024-08-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='post',
        ),
        migrations.AddField(
            model_name='banner',
            name='post_slug',
            field=models.CharField(default='5284410002-dasasddas', verbose_name='Post slug'),
            preserve_default=False,
        ),
    ]
