# Generated by Django 5.0.6 on 2024-08-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_remove_banner_post_banner_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
