# Generated by Django 5.0.6 on 2024-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(verbose_name='Pit it to the main page')),
                ('post_slug', models.CharField(verbose_name='Post slug')),
            ],
        ),
    ]
