# Generated by Django 5.0.6 on 2024-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_draftpost_size_post_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpost',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size preview (KB)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size preview (KB)'),
        ),
    ]
