# Generated by Django 5.0.6 on 2024-09-10 20:32

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_alter_draftpost_size_alter_post_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpost',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.UploadToClass('uploads/posts/drafts/previews'), verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.UploadToClass('uploads/posts/previews'), verbose_name='Preview'),
        ),
    ]
