# Generated by Django 5.0.6 on 2024-09-11 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_alter_draftpost_preview_alter_post_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
